### ISSUE TITLE
Record current window does not work

### ISSUE THREAD

**Issue by Suzie97** [dr-Styki/ScreenRec#33]
When I try to use the record current window option, it is not recorded.

**Comment by dr-Styki** [comment]
Hi @Suzie97 
Can you give me a little bit more information like OS version, type of machine (laptop/desktop), CPU, GPU(s), etc ... 
Thew issue appear with any app or only with one ? 
Also, is the current window a flatpak app and/or is it close to the edge of the screen ?

PS: Can you provide debug traces when the issue appear ?

**Comment by Suzie97** [comment]
This is a pretty rare bug. Maybe its because the app that is being recorded doesn't allow it. The screen goes black and the cursor moves like a glitch in the recording. Try recording a youtube video in firefox with ScreenRec.

**Comment by dr-Styki** [comment]
I know this issue, it's because the recorded window is close to the edge of the desktop. It come from the window's shadow being partially outside of the desktop. From the gstreamer point of view, the window is made of the window and it's shadow. So if you are close to the edge, you try to record a no completely visible window that's why gsteamer fail.

As a work around you can record the area instead of the window.

**Comment by Suzie97** [comment]
Can you fix it in future updates?

**Comment by dr-Styki** [comment]
Probably not, because that's linked to the way that elementary OS manage shadows.
